name: Cleanup GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-cleanup"
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup GitHub Pages
        run: |
          echo "🧹 Cleaning up GitHub Pages..."
          # Create empty directory
          mkdir -p empty-build
          echo '<html><head><title>Clearing Pages</title></head><body><h1>GitHub Pages cleared - rebuilding...</h1></body></html>' > empty-build/index.html

      - name: Upload empty artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: empty-build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4